name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # build-and-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.5.3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3.6.0
  #       with:
  #         node-version: 20.x

  #     - name: Setup pnpm
  #       run: |
  #         npm install -g pnpm
  #         pnpm install

  #     - name: Build app
  #       run: pnpm run build

  #     # - name: Run tests
  #     #   run: pnpm run test
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 20.x

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install
      
      - name: Set .env
        run: echo ${{ secrets.ENV_FILE }} >> .env

      - name: Build app
        run: pnpm run build
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      - name: Rsync into the server
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/chat.pancho.moe/
      
        
